# Generated by Django 5.0.6 on 2024-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercustomer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
