# Generated by Django 5.0.6 on 2024-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fareflex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='intasend_id',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='wallet',
            name='can_disburse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='label',
            field=models.CharField(default='payment', max_length=255),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
