# Generated by Django 5.0.6 on 2024-05-15 01:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fareflex', '0002_remove_wallet_balance_remove_wallet_intasend_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(default='payment', max_length=255)),
                ('details', models.CharField(default='payment', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(default='ma3-routes', max_length=255)),
                ('start_location', models.CharField(default='payment', max_length=255)),
                ('stop_location', models.CharField(default='payment', max_length=255)),
                ('distance', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(default='payment', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='payment', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareflex.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(default='payment', max_length=20)),
                ('driver_name', models.CharField(default='payment', max_length=50)),
                ('conductor_name', models.CharField(default='payment', max_length=50)),
                ('capacity', models.IntegerField(default=14)),
                ('status', models.BooleanField(default=True)),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fareflex.route')),
            ],
        ),
    ]
