import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import necessary modules and components
import React from "react";
import { Container } from "react-bootstrap";
import "./globals.css"// Assuming your global styles are in this file
import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head"; // Import Head component for setting <head> tags

// Define RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Set metadata */}
        <title>Flexpay</title>
        <meta name="description" content="Generated by create next app" />
        {/* Add viewport meta tag for responsive design */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Optionally, you can include another font */}
        {/* For example, to use the Roboto font */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" /> */}
      </Head>
      <body className={inter.className}>
        <Container>
          {/* Include Header and Footer components */}
          <Header />
          <AuthProvider>
          {children} {/* Render children components */}
          </AuthProvider>
          <Footer />
        </Container>
      </body>
    </html>
  );
}
