// Import necessary modules and components
import React from "react";
import { Container } from "react-bootstrap";
import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head"; // Import Head component for setting <head> tags
 // Assuming your global styles are in this file

// Define RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Set metadata */}
        <title>Flexpay</title>
        <meta name="description" content="Generated by create next app" />
        {/* Add viewport meta tag for responsive design */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* Optionally, you can include another font */}
        {/* For example, to use the Roboto font */}
        {/* <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" /> */}
      </Head>
      <body>
        <Container>
          {/* Include Header and Footer components */}
          <Header />
          {children} {/* Render children components */}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
