// Import necessary modules and components
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Container } from "react-bootstrap"; // Assuming you're using Bootstrap for the Container component
import Header from "./Header"; // Import Header component
import Footer from "./Footer"; // Import Footer component
import "./globals.css";

// Initialize Inter font
const inter = Inter({ subsets: ["latin"] });

// Define metadata
export const metadata: Metadata = {
  title: "Flexpay",
  description: "Generated by create next app",
};

// Define RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: inter }}>
        <Container>
          {/* Include Header and Footer components */}
          <Header />
          {children} {/* Render children components */}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
